/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  documentSidebar: [
    'overview',
    'quickstart',
    {
      type: 'category',
      label: 'LLMs',
      collapsible: true,
      collapsed: false,
      items: ['llms/OpenAI'],
    },
    {
      type: 'category',
      label: 'Plugin',
      collapsible: true,
      collapsed: false,
      items: ['plugin/plugin', 'plugin/plugin_selection', 'plugin/embedding'],
    },
    'compression',
    'configurations',
    'planner',
    'session',
    'run_pytest',
    'taskweaver_as_a_lib'
  ],
  
};

export default sidebars;
